# ========== 资料栏 ========== #
# avatar 团队头像
avatar: /avatar/OopStorm.jpg
# author 团队名
author: OopStorm
# signature 团队名下面的子标题
signature: 团队博客
# SNS 各种链接
social:
  email: 
  github: //github.com/oopstorm
  # wechat and qq should be a path of qr-code image
  wechat: 
  qq: 
  weibo: 
  zhihu: 
  douban: 
  facebook: 
  twitter: 
  instagram: 
  stack-overflow: 
  v2ex: 
  linkedin: 
  others: 
  rss: 
# member 成员 
friends:
  AlphaHinex: //alphahinex.github.io
  Snorlax: //2015lym.github.io
  friendC: 
# about 关于
about:
  enable: ture
  image: '/intro/about-bg.jpg'

# ========== 站点 ========== #
# 浏览器标题
SEO_title: OopStorm
# 主标题
main_title: OopStorm
# 子标题
subtitle: 客户中心 团队协作 追求突破 乐于分享 简单高效
# 首页顶部背景图
site_header_image: '/intro/index-bg.jpg'
# 文章顶部背景图
post_header_image: '/intro/post-bg.jpg'
# 404 背景图
_404_image: '/intro/404-bg.jpg'

# ========== 评论插件 ========== #
# 目前支持直接添加 Livere，Disqus，Gitment，畅言及友言，填写插件对应的字段即可启用。
# 如果想添加其他评论插件，在 custom.ejs 中添加即可。
comment:
  # Livere  site: https://livere.com/
  livere_uid: 
  # Disqus  site: https://disqus.com/
  disqus_shortname: 
  # Changyan  site: http://changyan.kuaizhan.com/
  changyan_appid: 
  changyan_conf: 
  # Gitment  site: https://github.com/imsun/gitment
  gitment_owner: 
  gitment_repo: 
  gitment_client_id: 
  gitment_client_secret: 
  # Youyan  site: http://www.uyan.cc/
  youyan_uid: 

# ========== 统计 ========== #
# 是否开启不蒜子阅读量统计
busuanzi: true
# 百度统计(填写siteID)
baidu_analytics:
# Google统计(填写siteID)
google_analytics:
# CNZZ统计
CNZZ_analytics:

# ========== 其他 ========== #
# 浏览器地址前的小标题
favicon: /assets/favicon.ico
# 首页的文章摘要字数(默认300，填0则不显示摘要)
truncate_length: 
# enable toc
toc: true
# intro height (默认是屏幕高度的50%, 可以直接输入其他数字)
index_intro_height: 50
post_intro_height: 50
about_intro_height: 50
